export const CONCEPTS = [
  { slug: "concept-01", image: "/course-concepts/concept-01.jpg", title: "Aerial Perspective", description: "A sweeping first look at the scale, rhythm, and open character envisioned for the course." },
  { slug: "concept-02", image: "/course-concepts/concept-02.jpg", title: "Championship Layout", description: "Generous fairways, strategic water, and a landscape designed to reward thoughtful play." },
  { slug: "concept-03", image: "/course-concepts/concept-03.jpg", title: "Resort & Fairway", description: "Golf and hospitality brought together in one destination beneath the Bicol landscape." },
  { slug: "concept-04", image: "/course-concepts/concept-04.jpg", title: "Lakeside Course", description: "Waterfront holes create memorable views and a distinctive challenge from tee to green." },
  { slug: "concept-05", image: "/course-concepts/concept-05.jpg", title: "Golden Hour", description: "A course experience shaped by warm light, wide horizons, and long afternoons outdoors." },
  { slug: "concept-06", image: "/course-concepts/concept-06.jpg", title: "Waterfront Greens", description: "Sculpted greens and reflective water bring drama and calm to every round." },
  { slug: "concept-07", image: "/course-concepts/concept-07.jpg", title: "The Grand Course", description: "An expansive championship landscape designed to feel both elevated and welcoming." },
  { slug: "concept-08", image: "/course-concepts/concept-08.jpg", title: "Signature Green", description: "Bold bunkering and considered contours frame a green made to be remembered." },
  { slug: "concept-09", image: "/course-concepts/concept-09.jpg", title: "Clubhouse Village", description: "A complete golf destination where the course, clubhouse, and community come together." },
  { slug: "concept-10", image: "/hero-4k.png", title: "Mt. Isarog Vision", description: "The defining idea for CamSur Uptown: championship golf meeting the spirit of Bicol." },
] as const;

export const SITE_SECTIONS = [
  {
    slug: "golf",
    label: "Golf",
    eyebrow: "The course",
    title: "Championship golf beneath Mt. Isarog",
    description: "Explore ten visual concepts shaping a distinctive new golf destination in Camarines Sur.",
    image: "/course-concepts/concept-01.jpg",
    links: CONCEPTS.map((concept, index) => ({ label: `Concept ${String(index + 1).padStart(2, "0")} — ${concept.title}`, href: `/golf/${concept.slug}` })),
  },
  {
    slug: "packages",
    label: "Packages",
    eyebrow: "Stay and play",
    title: "Build a golf escape worth remembering",
    description: "Flexible golf, dining, and accommodation experiences designed around your time at CamSur Uptown.",
    image: "/course-concepts/concept-05.jpg",
    links: ["Stay & Play", "Weekend Golf", "Group Getaways", "Corporate Golf", "Seasonal Offers"].map((label) => ({ label, href: "/packages" })),
  },
  {
    slug: "accommodations",
    label: "Accommodations",
    eyebrow: "Stay in style",
    title: "Rest close to the fairway",
    description: "Comfortable stays, warm Bicolano hospitality, and easy access to every part of the club.",
    image: "/course-concepts/concept-03.jpg",
    links: ["Fairway Villas", "Isarog Suites", "Clubhouse Lodge", "Uptown Hotel"].map((label) => ({ label, href: "/accommodations" })),
  },
  {
    slug: "dining",
    label: "Dining",
    eyebrow: "Taste of Bicol",
    title: "Good rounds deserve great tables",
    description: "From relaxed clubhouse meals to destination dining inspired by the flavors of the region.",
    image: "/course-concepts/concept-09.jpg",
    links: ["The Clubhouse", "Fairway Grill", "Private Dining", "Celebrations"].map((label) => ({ label, href: "/dining" })),
  },
  {
    slug: "visit",
    label: "Visit",
    eyebrow: "Plan your arrival",
    title: "Your CamSur Uptown journey starts here",
    description: "Find essential visitor information, directions, club guidelines, and ways to make the most of your day.",
    image: "/course-concepts/concept-07.jpg",
    links: ["Getting Here", "Guest Information", "Club Guidelines", "Contact the Club"].map((label) => ({ label, href: "/visit" })),
  },
  {
    slug: "events",
    label: "Events",
    eyebrow: "Gather at the club",
    title: "A remarkable setting for every occasion",
    description: "Tournaments, corporate gatherings, weddings, and celebrations surrounded by the course.",
    image: "/course-concepts/concept-06.jpg",
    links: ["Golf Tournaments", "Corporate Events", "Weddings", "Private Celebrations"].map((label) => ({ label, href: "/events" })),
  },
  {
    slug: "shop",
    label: "Shop",
    eyebrow: "The pro shop",
    title: "Bring the club with you",
    description: "Performance essentials, course-ready apparel, and considered CamSur Uptown keepsakes.",
    image: "/course-concepts/concept-08.jpg",
    links: ["Golf Apparel", "Equipment", "Accessories", "Club Gifts"].map((label) => ({ label, href: "/shop" })),
  },
] as const;

export type SiteSection = (typeof SITE_SECTIONS)[number];
